baseURL = 'https://lazarus-brasil.github.io/'
# baseURL = 'https://codezero.guiosoft.info/proxy/1313/'
languageCode = 'pt-br'
title = 'Lazarus Brasil Knowledge Base'
# theme = 'geekdoc'
theme = 'ananke'
